# Generated by Django 4.2.4 on 2023-08-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='nitrogen',
            new_name='N',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='phosphorus',
            new_name='P',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='potassium',
            new_name='k',
        ),
    ]
