# Generated by Django 4.2.4 on 2023-08-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_record_delete_crophistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
